<?php

namespace app\models;

use yii\base\Model;
use Yii;
use yii\db\ActiveRecord;
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class Subcategory extends ActiveRecord
{
    public static function tableName(): string {
        
        return 'subcategories';
    }

//    public static function className()
//    {
//        return 'Subcategory'; // TODO: Change the autogenerated stub
//    }

}
